name: hanabi_web
publish_to: "none"
description: Hanabi cooperative card game for Flutter Web.
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.5.11
  uuid: ^4.4.0

flutter:
  uses-material-design: true
